# Generated by Django 4.2.6 on 2023-10-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('is_active_change', 'Активировать или деактивировать рассылку')]},
        ),
    ]
