# Generated by Django 4.2.6 on 2023-10-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('is_active_change', 'Активировать или деактивировать пользователя')]},
        ),
    ]
