# Generated by Django 4.2.6 on 2023-10-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('toggle_is_active', 'Активировать или деактивировать пользователя')]},
        ),
    ]
