# Generated by Django 4.2.6 on 2023-10-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('closed', 'Завершена')], default='started', max_length=20, verbose_name='статус'),
        ),
    ]
