# Generated by Django 4.2.6 on 2023-10-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_mailing_send_date_mailing_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='start_date',
            new_name='date_run',
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='send_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='end_date',
        ),
    ]
