# Generated by Django 4.2.6 on 2023-10-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mailing_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('change_mailing_status', 'Активировать или деактивировать рассылку')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
