# Generated by Django 4.2.6 on 2023-10-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_start_date_mailing_date_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='server_response',
            field=models.CharField(blank=True, null=True, verbose_name='ответ от сервера'),
        ),
    ]
