# Generated by Django 4.2.6 on 2023-10-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('toggle_is_active', 'Активировать или деактивировать рассылку')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
