# Generated by Django 4.2.6 on 2023-10-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_mailing_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
